--select * from student
--drop table student


create table student(
id number(20,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
first_name varchar2(45) NOT NULL,
last_name varchar2(45) NOT NULL,
email varchar2(45) NOT NULL
);


INSERT INTO student(first_name, last_name, email) VALUES ('Mary','Public','mary@luv2code.com');
INSERT INTO student (first_name, last_name, email) VALUES ('John','Doe','john@luv2code.com');
INSERT INTO student (first_name, last_name, email) VALUES ('Ajay','Rao','ajay@luv2code.com');
INSERT INTO student (first_name, last_name, email) VALUES ('Bill','Neely','bill@luv2code.com');
INSERT INTO student (first_name, last_name, email) VALUES ('Maxwell','Dixon','max@luv2code.com');


